kind: Deployment
apiVersion: apps/v1
metadata:
  name: loghme7-back
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loghme7-back
  template:
    metadata:
      labels:
        app: loghme7-back
    spec:
      containers:
        - name: loghme7-back
          image: index.docker.io/tahashm/loghme:back
          imagePullPolicy: Always
          resources:
            requests:
              memory: "200Mi"
              cpu: "250m"
            limits:
              memory: "250Mi"
              cpu: "400m"
          ports:
            - containerPort: 80
      restartPolicy: Always
---
kind: Service
apiVersion: v1
metadata:
  name: loghme7-back
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      nodePort: 32001
  selector:
    app: loghme7-back